name: Process PNG Images and Invalidate CloudFront

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch
  workflow_dispatch:
      

jobs:
  process-images:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1  # Change this to your AWS region
      LAMBDA_FUNCTION_NAME: processImagesLambda  # Replace with your Lambda function name
      CLOUDFRONT_DISTRIBUTION_ID: EDXG1PIY342YH  # Replace with your CloudFront distribution ID

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Trigger Lambda Function
        run: |
          RESPONSE=$(aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME --region $AWS_REGION output.json --query 'StatusCode' --output text)
          if [ "$RESPONSE" != "200" ]; then
            echo "Lambda invocation failed! Response: $RESPONSE"
            exit 1
          fi
          echo "Lambda function executed successfully!"

      - name: Invalidate CloudFront Cache
        run: |
          INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" --query 'Invalidation.Id' --output text)
          echo "CloudFront invalidation triggered: $INVALIDATION_ID"
